# -*- coding: utf-8 -*-
"""File_handling_&_Numpy_Arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3DamFYzDrf1LzCD3wMP4AmKcaRNSKOQ

Task 1 — Create and Write to a File Create a file called warehouse_data.txt using the with statement. Write the following five values into it, one per line: 120, 85, 200, 95, 150. In a comment, explain what would happen if 'w' mode were replaced with 'a' mode on a second run of the same script.

Task 2 — Read the File Open warehouse_data.txt in read mode using the with statement. Read all lines into a list, strip the newline character from each, and print every value. In a comment, state which reading method you used and why it suits this task better than read() or readline().

Task 3 — Create a NumPy Array and Compute Statistics Convert the list of values into a 1D NumPy array of integers. Print the array, its dtype, shape, and size. Then print the sum, maximum, and minimum using NumPy operations. In a comment, explain what would happen to the dtype if one of the values in the file were the word 'error' instead of a number.
"""

#Task 1
import numpy as np
with open('warehouse_data.txt', 'w') as file:
    file.write("120\n85\n200\n95\n150\n")
"""If 'w' mode were replaced with 'a' mode on a second run, the new data would be appended to the end of the existing file rather than overwriting it.
The file would then contain 10 values instead of 5."""

#Task 2
data = []
with open('warehouse_data.txt', 'r') as file:
    lines = file.readlines()
    for line in lines:
        data.append(line.strip())
        print(line.strip())
"""I used the readlines() method. It suits this task better because it automatically splits the file into a list of strings based on line breaks, making it easy to iterate through and process each value."""

#Task 3
"""If one of the values were the word 'error', the dtype would change to a string type (e.g., '<U5') or 'object' because NumPy requires homogeneous data.
You would not be able to convert the array to integers directly, and mathematical operations like sum() would fail."""
arr = np.array(data, dtype=int)
print("Array:", arr)
print("dtype:", arr.dtype)
print("shape:", arr.shape)
print("size:", arr.size)
print("Sum:", np.sum(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))