# -*- coding: utf-8 -*-
"""Movie_Theatre_Booking_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15m48jTOJuJKqnmzjfDuIThTp9HxVHkSY

Question: Movie Theatre Booking System

Problem: Build a booking system for a 350-seat theatre that validates age

restrictions (12+ only) and seat availability.

Rules:

Theatre capacity: 350 seats (fixed)

Each booking: 1-15 tickets only

Age restriction: 12 years or above

Stop when: Theatre full OR user enters 0

Input: Repeatedly ask for the number of tickets (0 to exit), then the age of each person for valid bookings.

Output: Print booking status for each attempt, then final report showing total bookings, tickets sold, rejected bookings, and remaining seats.

Sample:

Input: 5, then ages: 15, 14, 13, 12, 11 → Output: BOOKING REJECTED - Age restriction

Input: 3, then ages: 20, 18, 16 → Output: BOOKING CONFIRMED - 3 tickets

Input: 0 → Final Report: Total Bookings: 1, Total Tickets Sold: 3, Rejected Bookings: 1, Remaining Seats: 347

Requirements: Use a while loop (main booking), continue statement (skip invalid tickets), for loop (check ages), and break statements (exit loops when needed).
"""

capacity = 350
total_bookings = 0
tickets_sold = 0
rejected_bookings = 0
tickets = 1
while tickets != 0:
  no_of_seats = int(input("Enter no.of tickets ('0' to exit): "))
  if no_of_seats < 0 or no_of_seats > 15:
    print("Warning: Each booking: 1-15 tickets only!!")
    continue
  if no_of_seats == 0 or capacity == tickets_sold:
    print("Final Report: Total Bookings: {}, Total Tickets Sold: {}, Rejected Bookings: {}, Remaining Seats: {}".format(total_bookings,tickets_sold,rejected_bookings,(capacity-tickets_sold)))
    break
  if no_of_seats <= (capacity-tickets_sold):
    a = True
    for i in range(no_of_seats):
      age = int(input("Enter the age of person: "))
      if age < 12:
        print("Output: BOOKING REJECTED - Age restriction")
        a = False
        rejected_bookings += 1
        break
    if a:
      total_bookings += 1
      tickets_sold += no_of_seats
      print("Output: BOOKING CONFIRMED -",no_of_seats,"tickets")