# -*- coding: utf-8 -*-
"""Numerical_Computing_with_Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppb8-VduOFiUkLWXxgIPxD4sy8-YMi-_

Task 1 — Generate and Inspect the Dataset Using NumPy random functions, create the following columns for 10 students: name (chosen randomly from a list of 5 names), age (random integers between 15 and 18), maths (random integers between 40 and 100), science (random integers between 40 and 100), and english (random integers between 40 and 100). Set np.random.seed(42) before generating any values. Print the shape of the marks array (only the three subject columns) and its dtype.

Task 2 — Reshape and Slice the Marks Array Take the marks array of shape (10, 3) and reshape it into shape (2, 5, 3). Print the reshaped array. Then, from the original (10, 3) marks array, slice and print the marks of the first five students for maths and science only (columns 0 and 1). In a comment, explain what the shape (2, 5, 3) represents in terms of the data.

Task 3 — Save the Records to a File Write all 10 student records to a text file called student_records.txt, with each record on its own line in the format: Name | Age | Maths | Science | English. Use the with statement to open the file. Print a confirmation message after writing. Then open the file in read mode and print all lines to verify the output.
"""

#Task 1
import numpy as np
np.random.seed(42)
students = ["Alice", "Bob", "Charlie", "David", "Eve"]
names = np.random.choice(students, 10)
age = np.random.randint(15, 19, 10)
maths = np.random.randint(40, 101, 10)
science = np.random.randint(40, 101, 10)
english = np.random.randint(40, 101, 10)
marks = np.column_stack((maths, science, english))
print(f"Shape of marks array: {marks.shape}")
print(f"Dtype of marks array: {marks.dtype}")

#Task 2
marks_1 = marks.reshape(2, 5, 3)
print(marks_1)
sliced_marks = marks[:5, :2]
print(sliced_marks)

#Task 3
with open("student_records.txt", "w") as file:
    for i in range(10):
        record = f"{names[i]} | {age[i]} | {maths[i]} | {science[i]} | {english[i]}\n"
        file.write(record)
print("\nStudent records written to 'student_records.txt' successfully.")
with open("student_records.txt", "r") as file:
    lines = file.readlines()
    for line in lines:
        print(line.strip())