# -*- coding: utf-8 -*-
"""Numpy_Numerical_foundations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SP51kIOpMvJWnWx3PpKDzthk9udTys_w

Task 1 — Tuples Create a tuple of five city names, unpack it into five separate variables, and print each variable. Then try to modify the first element and handle the resulting error with a try-except block that prints a clear message.

Task 2 — Sets Create two sets — one for students who passed a Python test and one for students who passed a SQL test. Print the union, intersection, and difference (Python-only passers) using set operators.

Task 3 — Lists and ASCII Create a list of five integers representing ASCII values. Use a loop with chr() to print each integer alongside its corresponding character. Then use ord() to retrieve and print the ASCII value of the character 'Z'.

Task 4 — Subprocess Use the subprocess module to run the shell command whoami and print the captured output using result.stdout.
"""

import subprocess
#Task 1
cities = ("Bengaluru","Chennai","Hyderabad","Mumbai","Delhi")
city1,city2,city3,city4,city5 = cities
print(city1, city2, city3, city4, city5)
try:
  cities[0] = "Kolkata"
except:
  print("Tuples are immutable")

# Task 2
set1 = {"Ram","Sita","Laxman","Bharat"}
set2 = {"Sita","Gita","Bharat","Hari"}
set3 = set1 | set2
set4 = set1 & set2
set5 = set1 - set2
print("Union:",set3)
print("Intersection: ",set4)
print("Difference(Python only passers):", set5)

#Task3
lis = [80,89,84,72,79,78]
for i in lis:
  print(chr(i),end = " ")
print("\n",ord('Z'))

#Task 4
result = subprocess.run(['whoami'], capture_output=True, text=True)
print(f"Current User: {result.stdout}")