# -*- coding: utf-8 -*-
"""Python_functions_and_lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uqAd9oC5DgHhF1l1WPXeQVeYs9jhFY54

You are building a simple marks analysis utility. Complete the following tasks in order.

Task 1. Write a function calculate_total(marks) that accepts a list of marks and returns their sum.

Task 2. Write a function calculate_average(marks) that calls calculate_total() and returns the average.

Task 3. Write a function get_grade(average) that returns "A" if average > 90, "B" if average > 75, and "C" otherwise.

Task 4. Write a function display_report(marks) that calls all three functions above and prints:

Total: {value}

Average: {value}

Grade: {value}

Task 5. Add a docstring to each function describing what it does.

Test your solution with the list [88, 76, 95, 60, 82].
"""

def calculate_total(marks):
  """function that accepts a list of marks and returns their sum"""
  return sum(marks)
def calculate_average(marks):
  """function that calls calculate_total() and returns the average"""
  total = calculate_total(marks)
  return total/len(marks)
def get_grade(average):
  """function that returns "A" if average > 90, "B" if average > 75, and "C" otherwise"""
  if average > 90:
    return "A"
  elif average  > 75:
    return "B"
  else:
    return "C"
def display_report(marks):
  """function that calls all three functions above and prints: Total,Average and Grade"""
  total = calculate_total(marks)
  average = calculate_average(marks)
  grade = get_grade(average)
  print("Total:",total)
  print("Average:",average)
  print("Grade:",grade)
"""Dynamic Input:
marks = []
n = int(input("Total no. of subjects: "))
for i in range(n):
  a = int(input("Enter subject marks:"))
  marks.append(a) """
marks = [88, 76, 95, 60, 82]
display_report(marks)